---
title: "hw6"
format: html
bibliography: references.bib
link-citations: true
author: "Cheyna & Erika & Kyla"
date: "2023-5-25"
editor: visual
execute: 
  eval: true # evaluates code
  echo: false # does not show code
  warning: false # does not show warnings
  error: false #does not print errors
fig-width: 6.5
fig-height: 8
---

```{r}
#Library Packages
library(here)
library(janitor)
library(rio)
library(ggplot2)
library(knitr)
library(kableExtra)
library(dplyr)


```

```{r}
# Import Data
star <- import(here("data", "star.csv")) %>%  
  clean_names()
```

To complete this homework, we are using several packages and R (@rio2023, @janitor2024, @here2020, @2023R, @knitr2025, @dplyr2023, @kableExtra2024)

```{r}
# recreating the table 

kable_table <- star %>%
  group_by(sex, frl) %>%
  summarise(
    math_mean = mean(tmathss, na.rm = TRUE),
    math_sd   = sd(tmathss, na.rm = TRUE),
    rdg_mean  = mean(treadss, na.rm = TRUE),
    rdg_sd    = sd(treadss, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  kable(booktabs = TRUE, digits = 2) %>%
  kable_styling(full_width = FALSE)

print(kable_table)

```

```{r}
# Create a plot of teacher experience vs math scores
star |> 
  ggplot(aes(x = totexp, y = tmathss)) +
  geom_point(color = "darkgrey") +
  geom_smooth(method = "lm", aes(color = frl)) +
  labs(x = "Teacher Experience (years)",
       y = "Total Math Scale Score",
       title = "Relation between teacher experience and math scores",
       subtitle = "Separate regression lines displayed by free/reduced price lunch status") +
  theme_minimal() +
  scale_color_discrete(name = "Lunch status", 
                      labels = c("Free/Reduced Price Meals", "Paid Meals")) +
  theme(legend.position = "bottom")
```

Based on the above figure, it seems that teacher experience has little to no effect on total math scale scores. However, we do see that students with free/reduced price meals have slightly better math scores than those students with paid meals.

# References
